version: "3.9"

services:
  backend:
    image: jsidla/borsibaar-backend:v1
    container_name: borsibaar-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - borsibaar-network

  frontend:
    image: jsidla/borsibaar-frontend:v1
    container_name: borsibaar-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - borsibaar-network
    depends_on:
      - backend

networks:
  borsibaar-network:
